{% set version = "0.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgnet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgnet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgnet/pkgnet_{{ version }}.tar.gz
  sha256: 7bbf5dab94463e6e07d1f51da5b9f161fd5b6ac91ef9e8ad7e0a2063f52d2b78

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dt
    - r-r6
    - r-assertthat
    - r-covr
    - r-data.table
    - r-futile.logger
    - r-glue
    - r-igraph
    - r-knitr
    - r-magrittr
    - r-rlang
    - r-rmarkdown >=1.9
    - r-visnetwork
  run:
    - r-base
    - r-dt
    - r-r6
    - r-assertthat
    - r-covr
    - r-data.table
    - r-futile.logger
    - r-glue
    - r-igraph
    - r-knitr
    - r-magrittr
    - r-rlang
    - r-rmarkdown >=1.9
    - r-visnetwork

test:
  commands:
    - $R -e "library('pkgnet')"           # [not win]
    - "\"%R%\" -e \"library('pkgnet')\""  # [win]

about:
  home: https://github.com/UptakeOpenSource/pkgnet, https://uptakeopensource.github.io/pkgnet/
  license: BSD_3_clause
  license_file: LICENSE
  summary: Tools from the domain of graph theory can be used to quantify the complexity and vulnerability to failure of a software package. That is the guiding philosophy of this package. 'pkgnet' provides tools to analyze the dependencies between functions in an R package and between its imported packages.
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pkgnet
# Type: Package
# Title: Get Network Representation of an R Package
# Version: 0.4.0
# Authors@R: c( person("Brian", "Burns", email = "brian.burns@uptake.com", role = c("aut", "cre")), person("James", "Lamb", email = "james.lamb@uptake.com", role = c("aut")), person("Patrick", "Boueri", email = "patrick.boueri@uptake.com", role = c("ctb")), person("Jay", "Qi", email = "jay.qi@uptake.com", role = c("aut")) )
# Maintainer: Brian Burns <brian.burns@uptake.com>
# Description: Tools from the domain of graph theory can be used to quantify the complexity and vulnerability to failure of a software package. That is the guiding philosophy of this package. 'pkgnet' provides tools to analyze the dependencies between functions in an R package and between its imported packages.
# Imports: assertthat, covr, data.table, DT, futile.logger, glue, igraph, knitr, magrittr, methods, R6, rlang, rmarkdown(>= 1.9), tools, visNetwork
# Suggests: devtools, testthat, withr
# License: BSD_3_clause + file LICENSE
# URL: https://github.com/UptakeOpenSource/pkgnet, https://uptakeopensource.github.io/pkgnet/
# BugReports: https://github.com/UptakeOpenSource/pkgnet/issues
# LazyData: TRUE
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-04-05 15:39:26 UTC; bburns
# Author: Brian Burns [aut, cre], James Lamb [aut], Patrick Boueri [ctb], Jay Qi [aut]
# Repository: CRAN
# Date/Publication: 2019-04-05 21:10:03 UTC
